import type { Metadata } from "next";
import "./globals.css";
import React from "react";

export const metadata: Metadata = {
  title: "The blog - Este é um blog com next.js",
  description: "Generated by create next app",
};

type RoutLayoutProps = {
  children: React.ReactNode;
};

export default function RootLayout({ children }: Readonly<RoutLayoutProps>) {
  return (
    <html lang="pt-br">
      <body>{children}</body>
    </html>
  );
}
