import type { Metadata } from "next";
import "./globals.css";
import React from "react";
import { Container } from "@/components/Container";
import { Header } from "@/components/Header";

export const metadata: Metadata = {
  title: {
    default: "The blog - Este é um blog com next.js",
    template: "%s | The Blog",
  },
  description: "Generated by create next app",
};

type RoutLayoutProps = {
  children: React.ReactNode;
};

export default function RootLayout({ children }: Readonly<RoutLayoutProps>) {
  return (
    <html lang="pt-br">
      <body>
        <Container>
          <Header />
          {children}
          <footer>
            <p className="text-6xl font-bold text-center py-8">Footer</p>
          </footer>
        </Container>
      </body>
    </html>
  );
}
